apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init
  annotations:
    "helm.sh/resource-policy": "keep"
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      labels:
        component: {{ .Release.Name }}-init
        stolon-cluster: {{ .Release.Name }}-{{ .Release.Namespace }}
    spec:
      {{ if .Values.global.serviceAccount.name }}serviceAccountName: {{ .Values.global.serviceAccount.name }}{{ else }}serviceAccountName: default{{ end }}
      {{ if .Values.global.imagePullSecrets }}imagePullSecrets:
        {{ range .Values.global.imagePullSecrets }}
          - {{ . | toYaml}}
        {{ end }}{{ end }}
      restartPolicy: Never
      containers:
        - name: {{ .Release.Name }}-init
          image: {{ if .Values.global.image_repo }}{{ .Values.global.image_repo }}/{{ end }}sorintlab/stolon:master-pg{{ .Values.global.postgres_version }}
          command:
            - "stolonctl"
            - "init"
            - "--log-level=debug"
            - "-f"
            - "/srv/stolon-init/init.json"
            - "-y"
          env:
            - name: STOLONCTL_CLUSTER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['stolon-cluster']
            - name: STOLONCTL_STORE_BACKEND
              value: "kubernetes"
            - name: STOLONCTL_KUBE_RESOURCE_KIND
              value: "configmap"

          volumeMounts:
            - name: {{ .Release.Name }}-init
              mountPath: "/srv/stolon-init"
              readOnly: true
      volumes:
        - name: {{ .Release.Name }}-init
          configMap:
            name: {{ .Release.Name }}-init
