apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
  name: {{ .Release.Name }}-init
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  init.json: |
    {"initMode": "new"
    {{- if .Values.global.pgSettings -}}
     "pgSettings":
         {{ toJson .Values.global.pgSettings }},
    {{ end }}
    }
