{{ if .Values.global.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}

rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - events
    verbs:
      - "*"
{{ end }}
