{{ if .Values.databases }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}

  name: {{ .Release.Name }}-databases
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  script.sh: |
    #!/bin/bash
    {{- if .Values.databases }}
    {{- range $database := .Values.databases }}
    {{ include "proxy.connect" . }} {{ printf "-c 'CREATE USER \"%s\";'" $database.name }}
    echo """ALTER USER \"{{ $database.name }}\" WITH PASSWORD '{{ if $database.password }}{{ $database.password }}{{ else }}{{ randAlphaNum 30 }}{{ end }}'""" | {{ include "proxy.connect" . }}
    {{ include "proxy.connect" . }} {{ printf "-c 'CREATE DATABASE \"%s\";'" $database.name }}
    {{ include "proxy.connect" . }} {{ printf "-c 'ALTER DATABASE \"%s\" OWNER TO \"%s\";'" $database.name $database.name }}
    {{- end }}
    {{- end }}
{{ end }}
