{{ if .Values.databases }}
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  namespace: {{ .Release.Name }}

  name: databases
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  script.sh: |
    #!/bin/bash
    export ROOT_PASSWORD=$(cat /etc/secrets/stolon/password)
    {{ if .Values.databases }}{{ range $database := .Values.databases }}{{ if $database.password }}
    {{ printf "psql postgresql://stolon:%s@stolon-proxy-service:5432/postgres -c \"CREATE USER %s WITH PASSWORD '%s'\";" "${ROOT_PASSWORD}" $database.name $database.password }}{{ else }}{{ printf "psql postgresql://stolon:%s@stolon-proxy-service:5432/postgres -c \"CREATE USER %s WITH PASSWORD '%s'\";" "${ROOT_PASSWORD}" $database.name (randAlphaNum 30) }}{{ end }}
    {{ printf "psql postgresql://stolon:%s@stolon-proxy-service:5432/postgres -c 'CREATE DATABASE %s';" "${ROOT_PASSWORD}" $database.name }}
    {{ printf "psql postgresql://stolon:%s@stolon-proxy-service:5432/postgres -c 'ALTER DATABASE %s OWNER TO %s';" "${ROOT_PASSWORD}" $database.name $database.name }}
    {{ end }}{{ end }}
{{ end }}