{{ if .Values.databases }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-db-create
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "{{ .Values.databases_creation_schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            name: {{ .Release.Name }}-db-create
            stolon-cluster: {{ include "stolon.cluster" . }}
        spec:
        {{ include "stolon.pullsecrets" . | indent 8 }}
        restartPolicy: Never
          initContainers:
            - name: cluster
              imagePullPolicy: IfNotPresent
              image: {{ include "sidecar.image" . }}
              command:
                - sh
                - '-c'
                - |
                  echo trying to contact stolon-proxy-service 5432
                  until nc -vzw 1 stolon-proxy-service 5432; do
                    echo "waiting for stolon cluster..."
                    sleep 2
                  done

            - name: pg-check
              image: {{ include "stolon.image" . }}
              command:
                - "/bin/bash"
                - "-ec"
                - |
                  export ROOT_PASSWORD=$(cat /etc/secrets/stolon/password)
                  until psql postgresql://stolon:${ROOT_PASSWORD}@{{ .Release.Name }}-proxy-service:5432/postgres -c "SELECT datname FROM pg_database;"; do
                    echo "waiting for stolon cluster..."
                    sleep 2
                  done

              volumeMounts:
                {{- include "stolon.passwordMount" . | indent 16 }}

          containers:
            - name: stolon-db-create
              image: {{ include "stolon.image" . }}
              command:
                - "/etc/databases/script.sh"
              volumeMounts:
                {{- include "stolon.passwordMount" . | indent 16 }}
                - mountPath: /etc/databases
                  name: databases
          volumes:
            - name: stolon
              secret:
                secretName: {{ .Release.Name }}
            - name: databases
              configMap:
                name: {{ .Release.Name }}-databases
                defaultMode: 0755
{{ end }}
