{{- if or .Values.databases .Values.additionalUser }}
{{- if .Values.secrets_refresh_schedule }}
apiVersion: batch/v1beta1
kind: CronJob
{{- else }}
apiVersion: batch/v1
kind: Job
{{- end }}
metadata:
  name: {{ .Release.Name }}-init
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.secrets_refresh_schedule }}
spec:
  schedule: "{{ .Values.databases_creation_schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            name: {{ .Release.Name }}-db-create
            stolon-cluster: {{ .Release.Name }}
        spec:
{{- else }}
spec:
  template:
    metadata:
      labels:
        component: {{ .Release.Name }}-init
        stolon-cluster: {{ .Release.Name }}-{{ .Release.Namespace }}
    spec:
{{- end }}
          serviceAccountName: {{ include "stolon.serviceAccount" . }}
          {{ include "stolon.pullsecrets" . | indent 10 }}
          restartPolicy: Never
          initContainers:
            - name: cluster
              imagePullPolicy: IfNotPresent
              image: {{ include "sidecar.image" . }}
              command:
                - sh
                - '-c'
                - |
                  echo trying to contact ${PGHOST} 5432
                  until nc -vzw 1 ${PGHOST} 5432; do
                    echo "waiting for stolon cluster..."
                    sleep 2
                  done
              env:
                {{- include "psql.ctl" . | indent 16 }}
              {{- if .Values.initResources }}
              resources:
                {{- toYaml .Values.initResources | nindent 16 }}
              {{- end }}

            - name: pg-check
              image: {{ include "stolon.image" . }}
              command:
                - "/bin/bash"
                - "-ec"
                - |
                  until {{ include "check.proxy" . }} ; do
                    echo "waiting for stolon cluster..."
                    sleep 2
                  done
              env:
                {{- include "psql.ctl" . | indent 16 }}
                - name: STKEEPER_PG_SU_PASSWORDFILE
                  value: "/etc/secrets/stolon/password"
              volumeMounts:
                {{- include "stolon.mounts" . | indent 16 }}
              {{- if .Values.initResources }}
              resources:
                {{- toYaml .Values.initResources | nindent 16 }}
              {{- end }}

          containers:
            - name: stolon-db-create
              image: {{ include "stolon.image" . }}
              command:
                - "/etc/databases/script.sh"
              env:
                {{- include "psql.ctl" . | indent 16 }}
                - name: STKEEPER_PG_SU_PASSWORDFILE
                  value: "/etc/secrets/stolon/password"
              volumeMounts:
                {{- include "stolon.mounts" . | indent 16 }}
                - mountPath: /etc/databases
                  name: databases

              {{- if .Values.initResources }}
              resources:
                {{- toYaml .Values.initResources | nindent 16 }}
              {{- end }}

          volumes:
            {{- include "stolon.configVolumes" . | indent 12 }}
            - name: databases
              configMap:
                name: {{ .Release.Name }}-databases
                defaultMode: 0755
{{- end }}