apiVersion: v1
kind: Service
metadata:
  name: stolon-proxy-service
  namespace: {{ .Release.Name }}

spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    component: stolon-proxy
    stolon-cluster: {{ .Release.Name }}
