apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ include "stolon.rootPassword" . | b64enc }}
