apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ include "stolon.rootPassword" . | b64enc }}
  replpassword: {{ include "stolon.replicaPassword" . | b64enc }}
