apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ include "stolon.rootPassword" . | b64enc }}
  replpassword: {{ include "stolon.replicaPassword" . | b64enc }}
  {{- if .Values.databases }}
  {{- range $database := .Values.databases  }}
  database-{{ $database.name }}: {{ if $database.password }}{{ $database.password | b64enc }}{{ else }}{{ randAlphaNum 30 | b64enc }}{{ end }}
  {{- end }}
  {{- end }}

  {{- if .Values.additionalUser }}
  {{- range $user := .Values.additionalUser  }}
  user-{{ $user.name }}: {{ if $user.password }}{{ $user.password | b64enc }}{{ else }}{{ randAlphaNum 30 | b64enc }}{{ end }}
  {{- end }}
  {{- end }}
