apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-proxy
  namespace: {{ .Release.Namespace }}

spec:
  replicas: {{ .Values.proxy_replicas }}
  selector:
    matchLabels:
      component: stolon-proxy
      stolon-cluster: {{ include "stolon.cluster" . }}
  template:
    metadata:
      labels:
        component: stolon-proxy
        stolon-cluster: {{ include "stolon.cluster" . }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: {{ include "stolon.serviceAccount" . }}
      {{ include "stolon.pullsecrets" . | indent 6 }}
      initContainers:
        - name: check-sentinel
          imagePullPolicy: IfNotPresent
          image: {{ include "sidecar.image" . }}
          command:
            - sh
            - '-c'
            - |
              echo trying to contact {{ .Release.Name }}-sentinel-monitoring 8080
              until nc -vzw 1 {{ .Release.Name }}-sentinel-monitoring 8080; do
                echo "waiting for stolon cluster..."
                sleep 2
              done
          {{- if .Values.initResources }}
          resources:
            {{- toYaml .Values.initResources | nindent 12 }}
          {{- end }}

      containers:
        - name: proxy
          image: {{ include "stolon.image" . }}
          command:
            - "/bin/bash"
            - "-ec"
            - stolon-proxy
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STPROXY_CLUSTER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['stolon-cluster']
            - name: STPROXY_STORE_BACKEND
              value: "kubernetes"
            - name: STPROXY_KUBE_RESOURCE_KIND
              value: "configmap"
            - name: STPROXY_LISTEN_ADDRESS
              value: "0.0.0.0"
            - name: STPROXY_METRICS_LISTEN_ADDRESS
              value: "0.0.0.0:8080"
            {{- include "stolon.ctl" . | indent 12 }}
            {{- include "psql.ctl" . | indent 12 }}

          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
            - name: metrics
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            timeoutSeconds: 5

          {{- if .Values.proxyResources }}
          resources:
            {{- toYaml .Values.proxyResources | nindent 12 }}
          {{- end }}
