apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sentinel-monitoring
  namespace: {{ .Release.Namespace }}

spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    component: {{ .Release.Name }}-sentinel
    stolon-cluster: {{ .Release.Name }}-{{ .Release.Namespace }}
