apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sentinel
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.sentinel_replicas }}
  selector:
    matchLabels:
      component: stolon-sentinel
      stolon-cluster: {{ include "stolon.cluster" . }}
  template:
    metadata:
      labels:
        component: stolon-sentinel
        stolon-cluster: {{ include "stolon.cluster" . }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: {{ include "stolon.serviceAccount" . }}
      {{ include "stolon.pullsecrets" . | indent 6 }}
      containers:
        - name: sentinel
          image: {{ include "stolon.image" . }}
          command:
            - stolon-sentinel
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STSENTINEL_CLUSTER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['stolon-cluster']
            - name: STSENTINEL_STORE_BACKEND
              value: "kubernetes"
            - name: STSENTINEL_KUBE_RESOURCE_KIND
              value: "configmap"
            - name: STSENTINEL_METRICS_LISTEN_ADDRESS
              value: "0.0.0.0:8080"
            {{- include "stolon.ctl" . | indent 12 }}
            {{- include "psql.ctl" . | indent 12 }}

          ports:
            - containerPort: 8080

          volumeMounts:
            {{- include "stolon.mounts" . | indent 12 }}
      volumes:
        {{- include "stolon.configVolumes" . | indent 8 }}
