postgres_replicas: 3
proxy_replicas: 1
sentinel_replicas: 1

persistence:
  # storageClass: "-"
  size: 512Mi

global:
  postgres_version: 12
  busybox_tag: 1.32.0
  image_repo: ''
  imagePullSecrets: []
    #- name: secret1
    #- name: secret2
  pgSettings:
  serviceAccount:
    create: false
    #name: default
  rbac:
    create: false

cluster_name: "cluster.local"

databases: {} # databases created after installation
  #keycloak:
  #  name: keycloak
  #  password: # if empty or undefined, will be generated random password (30 symbols)
databases_creation_schedule: "*/2 * * * *"

openshift:
  enabled: false

postgres_password: ""  # system superuser password. if empty, will be generated random password (30 symbols)
replication_password: "" # system replication user password. if empty, will be generated random password (30 symbols)
