postgres_replicas: 3
proxy_replicas: 1
sentinel_replicas: 1
postgres_storage_size: 512Mi

global:
  postgres_version: 12
  busybox_tag: 1.32.0
  image_repo: ''
  imagePullSecrets: []
    #- name: secret1
    #- name: secret2
  pgSettings:
  serviceAccount:
    create: false

cluster_name: "cluster.local"

databases: {} # databases created after installation
  #keycloak:
  #  name: keycloak
  #  password: # if empty or undefined, will be generated random password (30 symbols)
databases_creation_schedule: "*/5 * * * *"

openshift:
  enabled: false

postgres_password: ""  # if empty, will be generated random password (30 symbols)
