postgres_replicas: 3
proxy_replicas: 1
sentinel_replicas: 1

persistence:
  # storageClass: "-"
  size: 512Mi

image:
  registry: docker.io
  repository: sorintlab/stolon
  tag: master # SorintLab Stolon release
  postgres: 12 # major PostgreSQL version
  pullPolicy: IfNotPresent
  #pullSecrets:

sidecar:
  registry: docker.io
  repository: busybox
  tag: "1.32.0"

serviceAccount:
  create: false
  #name: default

rbac:
  create: false

cluster_name: "cluster.local"

databases: {} # databases created after installation
  #keycloak:
  #  name: keycloak
  #  password: # if empty or undefined, will be generated random password (30 symbols)
databases_creation_schedule: "*/2 * * * *"

openshift:
  enabled: false

postgres_password: ""  # system superuser password. if empty, will be generated random password (30 symbols)
replication_password: "" # system replication user password. if empty, will be generated random password (30 symbols)
